### ISSUE TITLE
Hardcoded path to Cargo depends on rustup-specific binary location

### ISSUE THREAD

**Issue by werezak** [ImageOptim/ImageOptim#255]
I opened the ImageOptim.xcodeproj file and did a build as mentioned in the readme but got this error:

error: can't exec '/Users/user/.cargo/bin/cargo' (No such file or directory)

I did a "brew install rust" and that installed cargo but still got the error.

**Comment by kornelski** [comment]
Thanks for the report. It seems I implemented integration only in the way that supports Cargo installed via rustup. If you remove rust from brew and install via rustup, it should work.

I'll see if I can change it to work with Brew's Rust, too.

**Comment by werezak** [comment]
I tried it again:

brew uninstall rust
brew install rustup
rustup-init

and tried to build it again but the error was:

error: could not find `Cargo.toml` in `/Users/user/Downloads/ImageOptim-master/svgcleaner/src` or any parent directory

**Comment by kornelski** [comment]
It's probably incomplete git checkout. Try:

     git submodule update --init

**Comment by kornelski** [comment]
When you clone ImageOptim, always use `git clone --recursive`. Xcode build is set up to try to fix lack of `--recursive` flag in git, but it's always problematic.

**Comment by werezak** [comment]
I got further along this time using the `git clone --recursive`.  But it terminated with the following error in the `.../ImageOptim/Sparkle/Configurations/make-release-package.sh` bash script:

```
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cocoapods (LoadError)
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -:1:in `<main>'
Command /bin/bash failed with exit code 1
```

**Comment by kornelski** [comment]
That's bug https://github.com/sparkle-project/Sparkle/issues/860 The workaround is to install CocoaPods.

**Comment by marcolabreu** [comment]
Started again with `git clone --recurse-submodules`. Even with Homebrew Cocoapods already installed, I ran into the last error reported above. After `brew uninstall cocoapods` and `gem install cocoapods`, build succeeded. I guess that adds one additional requirement to the build instructions. :)
